<?php

/**
 * @file
 * Contains mollo_event.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mollo_event_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the mollo_event module.
    case 'help.page.mollo_event':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mollo Event') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mollo_event_theme()
{
  return [
    'mollo_event' => [
      'render element' => 'children',
    ],
  ];
}


function mollo_event_form_alter(&$form, &$form_state, $form_id)
{

  // Show Menu with Names on List Filter
  // - role
  // -
  // -
  if ($form['#id'] === 'views-exposed-form-event-dates-admin-list' ||
    $form['#id'] === 'views-exposed-form-roles-admin-list' ||
    $form['#id'] === 'views-exposed-form-leadership-admin-list'
  ) {

    $nids = \Drupal::entityQuery('node')->condition('type', 'mollo_event')->execute();
    $nodes = \Drupal\node\Entity\Node::loadMultiple($nids);
    $options = ['' => 'All'];

    foreach ($nodes as $nid => $node) {
      $value = $node->get('field_mollo_name')->getString();

      if (isset($value)) {
        $options[$value] = $value;
      }
    }

    if (isset($form['event'])) {
      $form['event']['#type'] = 'select';
      $form['event']['#options'] = $options;
      $form['event']['#size'] = 1;
    }
  }
}
